name: Auto Article Generator

# This workflow generates a Medium article using the Perplexity API and optionally
# publishes it via the Medium API. It runs on a fixed daily schedule and
# provides a manual trigger with inputs for full customisation. Secrets for
# PERPLEXITY_API_KEY and MEDIUM_TOKEN should be configured in the repository
# settings. Default values can be supplied via repository variables or by
# editing the defaults below.

on:
  schedule:
    # Daily at 06:00 UTC (adjust as needed).
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic of the article'
        required: false
        default: 'Serverless computing in India: pros and cons'
      publish:
        description: 'Publish to Medium (true|false)'
        required: false
        default: 'false'
      tags:
        description: 'Comma‑separated tags (max 5)'
        required: false
        default: ''
      audience:
        description: 'Audience level (beginner|intermediate|advanced)'
        required: false
        default: 'beginner'
      tone:
        description: 'Tone (friendly|professional|practical|conversational)'
        required: false
        default: 'practical'
      model:
        description: 'Perplexity model (sonar|sonar-reasoning|sonar-pro|sonar-deep-research)'
        required: false
        default: 'sonar'
      minutes:
        description: 'Estimated reading time'
        required: false
        default: '10'
      outline_depth:
        description: 'Outline depth (integer)'
        required: false
        default: '3'
      include_code:
        description: 'Include code snippets? (true|false)'
        required: false
        default: 'true'
      status:
        description: 'Medium publish status (draft|public|unlisted)'
        required: false
        default: 'draft'
      canonical_url:
        description: 'Canonical URL (optional)'
        required: false
        default: ''

concurrency:
  group: auto-article
  cancel-in-progress: false

jobs:
  autopilot:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
    steps:
      - uses: ./.github/actions/generate

  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
    steps:
      - uses: ./.github/actions/generate
        with:
          topic: ${{ github.event.inputs.topic }}
          publish: ${{ github.event.inputs.publish }}
          tags: ${{ github.event.inputs.tags }}
          audience: ${{ github.event.inputs.audience }}
          tone: ${{ github.event.inputs.tone }}
          model: ${{ github.event.inputs.model }}
          minutes: ${{ github.event.inputs.minutes }}
          outline_depth: ${{ github.event.inputs.outline_depth }}
          include_code: ${{ github.event.inputs.include_code }}
          status: ${{ github.event.inputs.status }}
          canonical_url: ${{ github.event.inputs.canonical_url }}

