name: Auto Article Generator

on:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: auto-article
  cancel-in-progress: false

jobs:
  generate:
    uses: ./.github/workflows/generate.yml
    secrets: inherit
    with:
      topic: >-
        ${{ vars.AUTO_TOPIC || 'Serverless computing in India: pros and cons' }}
      publish: ${{ vars.AUTO_PUBLISH || false }}
      tags: ${{ vars.AUTO_TAGS || '' }}
      audience: ${{ vars.AUTO_AUDIENCE || 'beginner' }}
      tone: ${{ vars.AUTO_TONE || 'practical' }}
      model: ${{ vars.AUTO_MODEL || 'sonar' }}
      minutes: ${{ vars.AUTO_MINUTES || 10 }}
      outline_depth: ${{ vars.AUTO_OUTLINE_DEPTH || 3 }}
      include_code: ${{ vars.AUTO_INCLUDE_CODE || true }}
      status: ${{ vars.AUTO_STATUS || 'draft' }}
      canonical_url: ${{ vars.AUTO_CANONICAL_URL || '' }}
