name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actionlint
        uses: rhysd/actionlint@v1

      - name: yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          yamllint .github/workflows/auto_article.yml .github/actions/generate/action.yml
