---
name: Generate article
'on':
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run generator
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -m app.cli generate 1 --db-key "$SUPABASE_KEY" --publish
