---
name: Auto Article Generator
'on':
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic of the article'
        required: false
        default: 'Serverless computing in India: pros and cons'
      publish:
        description: 'Publish to Medium (true or false)'
        required: false
        default: 'false'
      tags:
        description: 'Comma-separated tags'
        required: false
        default: ''
  schedule:
    - cron: '0 9 * * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/generate
        with:
          topic: ${{ inputs.topic }}
          publish: ${{ inputs.publish }}
          tags: ${{ inputs.tags }}
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
