name: Manual Article Generator

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic of the article'
        required: false
        type: string
        default: 'Serverless computing in India: pros and cons'
      publish:
        description: 'Publish to Medium?'
        required: false
        type: boolean
        default: false
      tags:
        description: 'Comma-separated tags (max 5)'
        required: false
        type: string
        default: ''
      audience:
        description: 'Audience level'
        required: false
        type: choice
        default: beginner
        options:
          - beginner
          - intermediate
          - advanced
      tone:
        description: 'Tone'
        required: false
        type: choice
        default: practical
        options:
          - friendly
          - professional
          - practical
          - conversational
      model:
        description: 'Perplexity model'
        required: false
        type: choice
        default: sonar
        options:
          - sonar
          - sonar-reasoning
          - sonar-pro
          - sonar-deep-research
      minutes:
        description: 'Estimated reading time'
        required: false
        type: number
        default: 10
      outline_depth:
        description: 'Outline depth (integer)'
        required: false
        type: number
        default: 3
      include_code:
        description: 'Include code snippets?'
        required: false
        type: boolean
        default: true
      status:
        description: 'Medium publish status'
        required: false
        type: choice
        default: draft
        options:
          - draft
          - public
          - unlisted

concurrency:
  group: auto-article
  cancel-in-progress: false

jobs:
  generate:
    uses: ./.github/workflows/generate.yml
    secrets: inherit
    with:
      topic: ${{ github.event.inputs.topic }}
      publish: ${{ github.event.inputs.publish }}
      tags: ${{ github.event.inputs.tags }}
      audience: ${{ github.event.inputs.audience }}
      tone: ${{ github.event.inputs.tone }}
      model: ${{ github.event.inputs.model }}
      minutes: ${{ github.event.inputs.minutes }}
      outline_depth: ${{ github.event.inputs.outline_depth }}
      include_code: ${{ github.event.inputs.include_code }}
      status: ${{ github.event.inputs.status }}
