name: Scheduled series publisher

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Series topic'
        required: true
      posts:
        description: 'Number of articles to plan'
        required: false
        default: '5'
      gap_hours:
        description: 'Hours between scheduled publications'
        required: false
        default: '24'
  schedule:
    - cron: "0 * * * *"

jobs:
  plan:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Plan series in database
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -m app.cli plan-series \
            --db-key "$SUPABASE_KEY" \
            --topic "${{ github.event.inputs.topic }}" \
            --posts "${{ github.event.inputs.posts }}" \
            --gap-hours "${{ github.event.inputs.gap_hours }}"

  generate:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Generate and publish next scheduled article
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -m app.cli auto \
            --db-key "$SUPABASE_KEY" \
            --publish
